name: gestao_demandas
description: Sistema de Gestão de Parcerias - Aginova - UFMS
publish_to: "none" # porque não vai pro pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  intl: ^0.19.0

  # Multiseleção
  multi_select_flutter: ^4.1.3

  # Exportar/compartilhar (mobile/desktop)
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  cross_file: ^0.3.4+2

  # Para baixar arquivo no Web (Blob/URL/AnchorElement)
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

