name: gestao_demandas
description: Sistema de Gestão de Parcerias - Aginova - UFMS
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  intl: ^0.19.0

  # Multiseleção de filtros
  multi_select_flutter: ^4.1.3

  # Opcional (se for usar compartilhar/exportar em mobile/desktop)
  # Se não for usar agora, pode comentar/remover.
  share_plus: ^10.0.2

flutter:
  uses-material-design: true

